name: poc-provision-vms-to-dtl-jy

pr: none

trigger: none

parameters:
  - name: app_name

variables:
  - group: vg-common-secret

pool:
  vmImage: vs2017-win2016
stages:
- stage: Provision
  jobs:
  - job: ProvisionVMToDTL
    strategy:
      maxParallel: 4
      matrix:
        TEST: 
          ENV: TEST
        INT:
          ENV: INT
        STG:
          ENV: STG
        PROD:
          ENV: PROD
    steps:
    - task: PowerShell@2
      displayName: 'generate_random_vm_prefix_name'
      inputs:
        targetType: filePath
        filePath: 'utils/powershell/executable/generate_random_vm_prefix_name.ps1'
        arguments: ''

    - task: CmdLine@2
      inputs:
        script: |
          echo Write your commands here
          
          echo Hello world
          
          echo $(ENV)

          echo $[parameters.app_name]

          echo $(vm_count)

    # - task: AzureResourceManagerTemplateDeployment@3
    #   inputs:
    #     deploymentScope: 'Resource Group'
    #     azureResourceManagerConnection: 'epp-cloud-infra (df518fea-1410-40b9-8d30-51d2c9eab0d7)'
    #     subscriptionId: 'df518fea-1410-40b9-8d30-51d2c9eab0d7'
    #     action: 'Create Or Update Resource Group'
    #     resourceGroupName: 'rg-testing-env-lab'
    #     location: 'West US 2'
    #     templateLocation: 'Linked artifact'
    #     csmFile: 'cd_machine\v1_epp_saas_1.0\azure_dtl_arm\dtl-vm-arm.json'
    #     deploymentMode: 'Incremental'
    #     overrideParameters: '-vm_prefix $(vm_prefix) -env_name $(ENV) -app_name $(app_name) -vm_10_notes "Windows 10 Enterprise, Version 2004" -vm_10_offer "Windows-10" -vm_10_sku "20h1-ent" -vm_16_notes "Windows Server 2016 Datacenter" -vm_16_offer "WindowsServer" -vm_16_sku "2016-Datacenter" -vm_os_type "Windows" -vm_size "Standard_B2ms" -vm_count $(vm_count) -user_name "trend" -password $(vm-pwd)'