name: poc-create-images-from-vms

pr: none

trigger: none

variables:
  - group: vg-common-secret

pool:
  vmImage: vs2017-win2016
stages:
- stage: Provision
  jobs:
  - job: ProvisionVMToDTL
    strategy:
      maxParallel: 4
      matrix:
        INT:
          ENV: int
        PROD:
          ENV: prod
        STG:
          ENV: stg
        TEST:
          ENV: test

    steps:

    - task: CmdLine@2
      inputs:
        script: |
          echo Write your commands here
          
          echo Hello world

          echo $(subscription_id)

          echo $(rg_name)
          
          echo $(ENV)

          echo $(app_name)
          
          echo $(vm_prefix)

    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'epp-cloud-infra ($(subscription_id))'
        subscriptionId: $(subscription_id)
        action: 'Create Or Update Resource Group'
        resourceGroupName: $(rg_name)
        location: 'West US 2'
        templateLocation: 'Linked artifact'
        csmFile: 'cd_machine\v1_epp_saas_1.0\azure_dtl_arm\dtl-img-arm.json'
        deploymentMode: 'Incremental'
        overrideParameters: '-subscription_id $(subscription_id) -rg_name $(rg_name) -vm_prefix $(vm_prefix) -env_name $(ENV) -app_name $(app_name) -vm_10_notes "Windows 10 Enterprise, Version 2004" -vm_10_offer "Windows-10" -vm_10_sku "20h1-ent" -vm_16_notes "Windows Server 2016 Datacenter" -vm_16_offer "WindowsServer" -vm_16_sku "2016-Datacenter" -vm_os_type "Windows" -vm_size "Standard_B2ms" -user_name "trend" -password $(vm-pwd)'