pr: none

trigger: none

variables:
- group: vg-common-secret

pool:
  vmImage: vs2017-win2016
stages:
- stage: Provision
  jobs:
  - job: ProvisionVMToDTL
    strategy:
      parallel: 4
    steps:
    - task: PowerShell@2
      displayName: 'generate_random_vm_prefix_name'
      inputs:
        targetType: filePath
        filePath: 'utils/powershell/executable/generate_random_vm_prefix_name.ps1'
        arguments: ''
