pr: none

trigger: none

variables:
- group: vg-common-secret

pool:
  vmImage: vs2017-win2016

steps:
- task: PowerShell@2
  displayName: 'generate_random_vm_prefix_name'
  inputs:
    targetType: filePath
    filePath: 'utils/powershell/executable/generate_random_vm_prefix_name.ps1'
    arguments: '-azure_devops_pat $(az-devops-pat-user) -env_type_and_product $(env_type_and_product)'